var a = "I am";
var b = "Rezaul Karim";
//console.log(a + " " + b);
var c = a.concat(" ", b);
//console.log(c);
var d = c.substr(8, 3);
//console.log(d);
//console.log(c.charAt(5));
//console.log(c.startsWith("I"));
//console.log(c.endsWith("m"));
//console.log(c.toUpperCase());
//console.log(c.toLowerCase());
//console.log("   Rezaul   ".trim());
console.log(c.split(""));
